spring:
  jpa:
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    pe.edu.unmsm.ciudadsana: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
