-- V001: Extensions y schemas
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS operacion;
CREATE SCHEMA IF NOT EXISTS telemetria;
CREATE SCHEMA IF NOT EXISTS ciudadano;
CREATE SCHEMA IF NOT EXISTS optimizacion;
CREATE SCHEMA IF NOT EXISTS prediccion;
CREATE SCHEMA IF NOT EXISTS kpi;
CREATE SCHEMA IF NOT EXISTS auditoria;
